---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "10"

os: linux
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
  jobs:
    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - EMBER_TRY_SCENARIO=ember-lts-2.16-ember-simple-auth-1.6
    - EMBER_TRY_SCENARIO=ember-lts-2.16-ember-simple-auth-2.0
    - EMBER_TRY_SCENARIO=ember-lts-2.18-ember-simple-auth-1.6
    - EMBER_TRY_SCENARIO=ember-lts-2.18-ember-simple-auth-2.0
    - EMBER_TRY_SCENARIO=ember-lts-3.4-ember-simple-auth-1.6
    - EMBER_TRY_SCENARIO=ember-lts-3.4-ember-simple-auth-2.0
    - EMBER_TRY_SCENARIO=ember-lts-3.4-ember-simple-auth-3.0
    - EMBER_TRY_SCENARIO=ember-lts-3.8-ember-simple-auth-1.6
    - EMBER_TRY_SCENARIO=ember-lts-3.8-ember-simple-auth-2.0
    - EMBER_TRY_SCENARIO=ember-lts-3.8-ember-simple-auth-3.0
    - EMBER_TRY_SCENARIO=ember-lts-3.12-ember-simple-auth-1.6
    - EMBER_TRY_SCENARIO=ember-lts-3.12-ember-simple-auth-2.0
    - EMBER_TRY_SCENARIO=ember-lts-3.12-ember-simple-auth-3.0
    - EMBER_TRY_SCENARIO=ember-lts-3.16-ember-simple-auth-1.6
    - EMBER_TRY_SCENARIO=ember-lts-3.16-ember-simple-auth-2.0
    - EMBER_TRY_SCENARIO=ember-lts-3.16-ember-simple-auth-3.0
    - EMBER_TRY_SCENARIO=ember-lts-3.20-ember-simple-auth-1.6
    - EMBER_TRY_SCENARIO=ember-lts-3.20-ember-simple-auth-2.0
    - EMBER_TRY_SCENARIO=ember-lts-3.20-ember-simple-auth-3.0
    - EMBER_TRY_SCENARIO=ember-release-ember-simple-auth-1.6
    - EMBER_TRY_SCENARIO=ember-release-ember-simple-auth-2.0
    - EMBER_TRY_SCENARIO=ember-release-ember-simple-auth-3.0
    - EMBER_TRY_SCENARIO=ember-beta-ember-simple-auth-1.6
    - EMBER_TRY_SCENARIO=ember-beta-ember-simple-auth-2.0
    - EMBER_TRY_SCENARIO=ember-beta-ember-simple-auth-3.0
    - EMBER_TRY_SCENARIO=ember-canary-ember-simple-auth-1.6
    - EMBER_TRY_SCENARIO=ember-canary-ember-simple-auth-2.0
    - EMBER_TRY_SCENARIO=ember-canary-ember-simple-auth-3.0

jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary-ember-simple-auth-1.6
    - env: EMBER_TRY_SCENARIO=ember-canary-ember-simple-auth-2.0
    - env: EMBER_TRY_SCENARIO=ember-canary-ember-simple-auth-3.0

before_install:
  - if [[ $NODE_VERSION ]]; then nvm install ${NODE_VERSION} && nvm use ${NODE_VERSION}; fi
  - npm config set spin false
  - npm install -g npm@6
  - npm --version

script:
  - npm run lint:js
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
